---
destination: public
source: src
exclude: ['node_modules']
title: Mayhem
timezone: UTC
collections:
  news:
    title: News
    output: true
    permalink: "/news/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: news
  values:
    layout: news
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: ''
twitter_username: mediamayhemTV
markdown: kramdown
theme: minima
sass:
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
navigation:
- title: about
  url: "/about"
- title: clients
  url: "/clients"
- title: contact
  url: "/contact"
