---
title: Mayhem
timezone: UTC
collections:
  news:
    title: News
    output: true
    permalink: "/news/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: news
  values:
    layout: news
exclude:
- Gemfile
- Gemfile.lock
email: hello@mediamayhemtv
description: We create award-winning content that delivers. Commercials, online, broadcast
  and fiction - all under one roof. Our stories are moving, entertaining and powerful.
  Welcome to Mayhem.
baseurl: ''
url: ''
twitter_username: mediamayhemTV
markdown: kramdown
theme: minima
sass:
gems:
- jekyll-feed
navigation:
- title: about
  url: "/about"
- title: clients
  url: "/clients"
- title: contact
  url: "/contact"
