---
title: Mayhem
timezone: UTC
collections:
  brands:
    title: Brands
    output: false
  posts:
    title: Posts
    output: true
  showcases:
    title: Showcases
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: showcases
  values:
    order: ''
    vimeoid: ''
    image: ''
    subtitle: ''
- scope:
    path: ''
    type: brands
  values:
    title: ''
    logo: ''
    clients:
    - 
    about: ''
    link: ''
- scope:
    path: ''
    type: posts
  values:
    layout: news
    brand: ''
    author: ''
    thumbnail-image: ''
    header-image: ''
    long: true
    video:
      is-visible: false
      vimeoid: ''
      image: ''
      title: ''
      subtitle: ''
      is-dark: false
permalink: "/:year/:month/:day/:title/"
exclude:
- Gemfile
- Gemfile.lock
email: hello@mayhemcreative.co.uk
description: We create award-winning content that delivers. Commercials, online, broadcast
  and fiction - all under one roof. Our stories are moving, entertaining and powerful.
  Welcome to Mayhem.
baseurl: 
url: 
twitter_username: mayhemcreative
markdown: kramdown
sass: 
gems:
- jekyll-feed
navigation:
- title: about
  url: "/about"
- title: clients
  url: "/clients"
- title: contact
  url: "/contact"
contact:
  general: hello@mayhemcreative.co.uk
  new-work: ian@mayhemcreative.co.uk
  telephone: "+44 207 193 7545 "
  address:
  - 15a  St George's Mews
  - Primrose Hill
  - London
  - NW1 8XE
clients:
- 20th Century Fox
- 2K Games
- Alpha LSG
- AMD
- Beko
- Boxnation
- Breitling
- BT Sport
- Cambridge University
- Clinique
- Condé Nast
- Deliveroo
- EA Sports
- Edelman
- Fuse International
- 'Grey London

'
- Grundig
- Innocent Smoothies
- Jigsaw
- Johnnie Walker
- Merceica
- NBA
- New York Knicks
- Nissan
- Olympus
- Qantas
- Reece's Pieces
- Time Out London
- Turnbull & Asser
- V&A Musuem
- Virgin Active
- Winsor & Newton
- WNBA
news-limit: 8
social-media:
- type: twitter
  url: https://twitter.com/mayhemcreative
- type: facebook
  url: https://www.facebook.com/mayhemcreative/
- type: instagram
  url: https://www.instagram.com/mayhem_creative/
- type: vimeo
  url: https://vimeo.com/mayhemuk
