---
title: Mayhem
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  showcase:
    title: Showcase
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: showcase
  values:
    order: ''
    vimeoid: ''
    image: ''
    subtitle: ''
- scope:
    path: ''
    type: posts
  values:
    layout: news
    author: ''
    thumbnail-image: ''
    header-image: ''
    long: true
    video:
      is-visible: false
      vimeoid: ''
      image: ''
      title: ''
      subtitle: ''
      is-dark: false
exclude:
- Gemfile
- Gemfile.lock
email: hello@mayhemcreative.co.uk
description: We create award-winning content that delivers. Commercials, online, broadcast
  and fiction - all under one roof. Our stories are moving, entertaining and powerful.
  Welcome to Mayhem.
baseurl: 
url: 
twitter_username: mayhemcreative
markdown: kramdown
sass: 
gems:
- jekyll-feed
navigation:
- title: about
  url: "/about"
- title: clients
  url: "/clients"
- title: contact
  url: "/contact"
contact:
  general: hello@mayhemcreative.co.uk
  new-work: ian@mayhemcreative.co.uk
  telephone: 0207 236 3451
  address:
  - 4th floor
  - 35/37 Ludgate Hill
  - City
  - EC4M 7JN
clients:
- 20th Century Fox
- 2K Games
- Alpha LSG
- BBC
- Beko
- Boxnation
- Breitling
- BT Sport
- Cambridge University
- Clinique
- Condé Nast
- Deliveroo
- Gentleman’s Journal
- Glastonbury
- Innocent Smoothies
- ITV Studios
- Jigsaw
- Merceica
- NBA
- Olympics 2012
- Olympus
- Red Bull
- Schauspiel Haus
- Team GB
- Time Out London
- Turnbull & Asser
- V&A Musuem
- Winsor & Newton
- Wrigley’s
news-limit: 8
social-media:
- type: twitter
  url: https://twitter.com/mayhemcreative
- type: facebook
  url: https://www.facebook.com/mayhemcreative/
- type: instagram
  url: https://www.instagram.com/mayhem_creative/
- type: vimeo
  url: https://vimeo.com/mayhemuk
